#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep  3 17:10:53 2023

@author: danielmaidana
"""

import numpy as np
import matplotlib.pyplot as plt 


S = np.array(['-','T', 'C', 'G', 'C'])  
T = np.array(['-','A', 'T', 'A', 'G', 'C']) 
DP_Matrix = np.empty([len(S), len(T)])


Gap = '-'
Match_Score = 1
Mismatch_Score = -1 
Gap_Score = -2

#------------------------------------------------------------------------------
## STEP 1 -> Index (0,0)
Step = 1

i = 0
j = 0 
Si = S[i]
Tj = T[j]

DP_Matrix[i,j] = 0 # Gap Penalty

Score_Matrix = np.empty([1,3]) # Equation Values
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('----------------------')
#------------------------------------------------------------------------------
## Index (1,0) 
Step = 2

i = 1
j = 0 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (2,0) 
Step = 3

i = 2
j = 0 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (3,0) 
Step = 4

i = 3
j = 0 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (4,0) 
Step = 5

i = 4
j = 0 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (0,1) 
Step = 6

i = 0
j = 1 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (0,2) 
Step = 7

i = 0
j = 2 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (0,3) 
Step = 8

i = 0
j = 3
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (0,4) 
Step = 9

i = 0
j = 4 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (0,5) 
Step = 10

i = 0
j = 5
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (1,1) 
Step = 11

i = 1
j = 1
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (2,1) 
Step = 12

i = 2
j = 1 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (3,1) 
Step = 13

i = 3
j = 1 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (4,1) 
Step = 14

i = 4
j = 1 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (1,2) 
Step = 15

i = 1
j = 2
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (2,2) 
Step = 16

i = 2
j = 2
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (3,2) 
Step = 17

i = 3
j = 2
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (4,2) 
Step = 18

i = 4
j = 2 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (1,3) 
Step = 19

i = 1
j = 3
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (2,3) 
Step = 20

i = 2
j = 3 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (3,3) 
Step = 21

i = 3
j = 3 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (4,3) 
Step = 22

i = 4
j = 3 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (1,4) 
Step = 23

i = 1
j = 4
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (2,4) 
Step = 24

i = 2
j = 4 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (3,4) 
Step = 25

i = 3
j = 4 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (4,4) 
Step = 26

i = 4
j = 4 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (1,5) 
Step = 27

i = 1
j = 5 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (2,5) 
Step = 28

i = 2
j = 5 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (3,5) 
Step = 29

i = 3
j = 5 
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
## Index (4,5) 
Step = 30

i = 4
j = 5
Si = S[i]
Tj = T[j]

if Si == Gap or Tj == Gap:  # Gap
    Alignment = Gap_Score
elif Si == Tj:              # Match
    Alignment = Match_Score 
else:                       # Mismatch
    Alignment = Mismatch_Score
print('Step', Step)
print('Index',i,',',j)
print('(Si,Tj)', Si, Tj)
print('Alignment', Alignment)    


# Equation 1
if i == 0 or j == 0:
    Eq1 = -100000000
    print('Eq1: Error')
else:
    Eq1 = DP_Matrix[i-1,j-1] + (Alignment)
    print('Eq1:', Eq1,'> Diagonal')
    
# Equation 2
if i == 0:
    Eq2 = -100000000
    print('Eq2: Error')
else:    
    Eq2 = DP_Matrix[i-1,j] + (Gap_Score)
    print('Eq2:', Eq2,'> Top')

# Equation 3
if j == 0:
    Eq3 = -100000000
    print('Eq3: Error')
else:   
    Eq3 = DP_Matrix[i,j-1] + (Gap_Score)
    print('Eq3:', Eq3,'> Left')


Score = max(Eq1, Eq2, Eq3)
print('Final Score',Score)
DP_Matrix[i,j] = Score
print('----------------------')
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

fig, ax = plt.subplots()
im = ax.imshow(DP_Matrix, cmap = 'Blues', interpolation='none')

xlabs = ['-','A', 'T', 'A', 'G', 'C']
ylabs = ['-','T', 'C', 'G', 'C']
ax.set_xticks(np.arange(len(xlabs)), labels = xlabs)
ax.set_yticks(np.arange(len(ylabs)), labels = ylabs)
plt.title("Q1: Dynamic Programming (Global)")

for i in range(len(T)):
    for j in range(len(S)+1):
        text = ax.text(j, i, round(DP_Matrix[i, j]),
                       ha = "center", va = "center", color = "black")
plt.show()   

